package dev.recordable;

import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.nio.file.Path;
import java.nio.file.StandardOpenOption;
import java.util.ArrayList;
import java.util.List;
import java.util.Locale;

/**
 * V1-0.06 Feature 3: Session Markers &amp; Chapters.
 *
 * <p>Pure-Java helper (shared across all variants) that converts the in-session
 * {@link RecordingBookmark} list into:</p>
 * <ul>
 *   <li>a human-readable sidecar {@code *_chapters.txt} timestamp file,</li>
 *   <li>an FFMETADATA1 file that ffmpeg can embed as real chapters via
 *       {@code -i meta.txt -map_metadata 1}.</li>
 * </ul>
 *
 * <p>Markers double as both quick bookmarks and chapter boundaries. Each marker's
 * timestamp is the start of a chapter; the chapter ends at the next marker (or the
 * end of the recording).</p>
 */
public final class ChapterManager {

    private ChapterManager() {}

    /** Strip the file extension from a path's filename. */
    private static String stem(Path videoFile) {
        String name = videoFile.getFileName().toString();
        int dot = name.lastIndexOf('.');
        return dot > 0 ? name.substring(0, dot) : name;
    }

    /** Format milliseconds as HH:MM:SS. */
    public static String formatTimestamp(long millis) {
        long totalSeconds = Math.max(0, millis) / 1000L;
        long h = totalSeconds / 3600L;
        long m = (totalSeconds % 3600L) / 60L;
        long s = totalSeconds % 60L;
        return String.format(Locale.ROOT, "%02d:%02d:%02d", h, m, s);
    }

    /**
     * Write a friendly {@code *_chapters.txt} sidecar listing every marker.
     * Returns the file path, or null if there were no markers / on failure.
     */
    public static Path writeChapterTextFile(Path videoFile, List<RecordingBookmark> markers) {
        if (videoFile == null || markers == null || markers.isEmpty()) return null;
        Path out = videoFile.resolveSibling(stem(videoFile) + "_chapters.txt");
        List<String> lines = new ArrayList<>();
        lines.add("Chapters / Markers for: " + videoFile.getFileName());
        lines.add("Generated by Record-able");
        lines.add("Tip: paste these into a YouTube description for clickable chapters.");
        lines.add("");
        int idx = 1;
        for (RecordingBookmark m : markers) {
            lines.add(formatTimestamp(m.timestampMs()) + "  " + safeLabel(m.description(), idx));
            idx++;
        }
        try {
            Files.write(out, lines, StandardCharsets.UTF_8,
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
            return out;
        } catch (IOException e) {
            RecordableMod.LOGGER.warn("ChapterManager: failed to write chapters file: {}", e.getMessage());
            return null;
        }
    }

    /**
     * Build an FFMETADATA1 file describing chapters, suitable for embedding with ffmpeg.
     * {@code totalDurationMs} is used to bound the final chapter.
     * Returns the metadata file path, or null if not enough markers / on failure.
     */
    public static Path writeFfmetadataFile(Path videoFile, List<RecordingBookmark> markers, long totalDurationMs) {
        if (videoFile == null || markers == null || markers.isEmpty()) return null;
        Path out = videoFile.resolveSibling(stem(videoFile) + "_ffmeta.txt");
        StringBuilder sb = new StringBuilder();
        sb.append(";FFMETADATA1\n");
        int idx = 1;
        for (int i = 0; i < markers.size(); i++) {
            long start = Math.max(0, markers.get(i).timestampMs());
            long end;
            if (i + 1 < markers.size()) {
                end = Math.max(start + 1, markers.get(i + 1).timestampMs());
            } else {
                end = Math.max(start + 1, totalDurationMs > 0 ? totalDurationMs : start + 1000);
            }
            sb.append("[CHAPTER]\n");
            sb.append("TIMEBASE=1/1000\n");
            sb.append("START=").append(start).append('\n');
            sb.append("END=").append(end).append('\n');
            sb.append("title=").append(escapeMeta(safeLabel(markers.get(i).description(), idx))).append('\n');
            idx++;
        }
        try {
            Files.write(out, sb.toString().getBytes(StandardCharsets.UTF_8),
                    StandardOpenOption.CREATE, StandardOpenOption.TRUNCATE_EXISTING, StandardOpenOption.WRITE);
            return out;
        } catch (IOException e) {
            RecordableMod.LOGGER.warn("ChapterManager: failed to write ffmetadata file: {}", e.getMessage());
            return null;
        }
    }

    /**
     * Embed chapters into an existing video file using ffmpeg (stream copy, no re-encode).
     * Produces a sibling "*_chaptered.<ext>"; returns the new path or null on failure.
     * Blocking call - run off the render thread.
     */
    public static Path embedChapters(Path videoFile, List<RecordingBookmark> markers, long totalDurationMs) {
        Path meta = writeFfmetadataFile(videoFile, markers, totalDurationMs);
        if (meta == null) return null;
        String ffmpeg = detectFfmpeg();
        if (ffmpeg == null || ffmpeg.isBlank()) {
            RecordableMod.LOGGER.warn("ChapterManager: ffmpeg unavailable, cannot embed chapters");
            return null;
        }
        String name = videoFile.getFileName().toString();
        int dot = name.lastIndexOf('.');
        String ext = dot > 0 ? name.substring(dot) : ".mkv";
        Path out = videoFile.resolveSibling(stem(videoFile) + "_chaptered" + ext);
        try {
            List<String> cmd = new ArrayList<>();
            cmd.add(ffmpeg);
            cmd.add("-y");
            cmd.add("-i"); cmd.add(videoFile.toString());
            cmd.add("-i"); cmd.add(meta.toString());
            cmd.add("-map_metadata"); cmd.add("1");
            cmd.add("-map_chapters"); cmd.add("1");
            cmd.add("-codec"); cmd.add("copy");
            cmd.add(out.toString());
            Process p = new ProcessBuilder(cmd).redirectErrorStream(true).start();
            try (var in = p.getInputStream()) { in.readAllBytes(); }
            int code = p.waitFor();
            if (code == 0 && Files.isRegularFile(out)) {
                return out;
            }
            RecordableMod.LOGGER.warn("ChapterManager: embed exited with code {}", code);
            Files.deleteIfExists(out);
        } catch (Exception e) {
            RecordableMod.LOGGER.warn("ChapterManager: embed failed: {}", e.getMessage());
        }
        return null;
    }

    private static String safeLabel(String desc, int idx) {
        if (desc == null || desc.isBlank()) return "Chapter " + idx;
        return desc.trim();
    }

    /** Escape characters special to FFMETADATA1 ( = ; # \ and newlines ). */
    private static String escapeMeta(String s) {
        return s.replace("\\", "\\\\")
                .replace("=", "\\=")
                .replace(";", "\\;")
                .replace("#", "\\#")
                .replace("\n", " ");
    }

    /**
     * Detects FFmpeg using a priority-based fallback chain:
     * <ol>
     *   <li>Bundled/downloaded FFmpeg (managed by {@link FfmpegBundleManager})</li>
     *   <li>RECORDABLE_FFMPEG_PATH environment variable</li>
     *   <li>System PATH (tries "ffmpeg" directly)</li>
     * </ol>
     */
    private static String detectFfmpeg() {
        String bundled = FfmpegBundleManager.getBundledFfmpegPath();
        if (bundled != null && !bundled.isBlank()) {
            return bundled;
        }
        String env = System.getenv("RECORDABLE_FFMPEG_PATH");
        if (env != null && !env.isBlank()) {
            Path p = Path.of(env.trim());
            if (Files.isExecutable(p)) {
                return p.toAbsolutePath().toString();
            }
        }
        try {
            ProcessBuilder pb = new ProcessBuilder("ffmpeg", "-version");
            pb.redirectErrorStream(true);
            Process proc = pb.start();
            if (proc.waitFor() == 0) {
                return "ffmpeg";
            }
        } catch (Exception ignored) {
        }
        return null;
    }
}
